### ISSUE TITLE
[BUG] 로그인 오류

### ISSUE THREAD

**Issue by Jay0727** [yeolsimee/MoneySaving-iOS#3]
매번 어플을 종료했다가 다시 어플 기동할때, 새롭게 로그인을 해야합니다.
어플 창을 안닫고 켜둔 상태로 1시간 정도 지나서 다시 어플 창을 열어도 로그인을 해야 한다고 떠요.
매번 어플을 열때마다 로그인을 해야하는 번거로움이 있습니다......

**Comment by KimVelVet** [comment]
Success
